name: Build

#
on: [push,workflow_dispatch]
#
jobs:
  build:
    runs-on: ubuntu-latest
    environment: token
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'liberica'
          server-id: github
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots deploy
        env:
          MAVEN_USERNAME: ${{ secrets.PUSH_USER }}
          MAVEN_PASSWORD: ${{ secrets.PUSH_TOKEN }}